DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_details CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  client INTEGER REFERENCES client(id) ON DELETE CASCADE,
  menu_item INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
  date TIMESTAMP,
);

CREATE TABLE order_details (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id INTEGER REFERENCES menu_item(id) ON DELETE CASCADE,
  quantity SMALLINT DEFAULT 1,
  special_requests TEXT,
  price NUMBER NOT NULL
);

CREATE TABLE reviews (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL,
  message TEXT
);


